# Generated by Django 4.1.7 on 2023-02-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id_cat', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='کلید اصلی')),
                ('name', models.CharField(max_length=25, verbose_name='نام دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='subCategories',
            fields=[
                ('id_subcat', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='کلید اصلی')),
                ('name', models.CharField(max_length=25, verbose_name='نام زیر دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id_product', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True, verbose_name='کلید اصلی')),
                ('name', models.CharField(max_length=25, verbose_name='نام محصول')),
                ('count', models.PositiveSmallIntegerField(verbose_name='تعداد محصول')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت محصول')),
                ('des', models.TextField(verbose_name='توضیحات')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categories', verbose_name='دسته بندی')),
            ],
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.subcategories', verbose_name='زیر دسته بندی'),
        ),
    ]
